/* This file generated by "run configure" */

const char *default_objdir = "../obj";
const char *default_bindir = "../bin";

const char *default_compile =
"gcc -c -Wall -Werror -ansi -O2 $(cfile) -o $(ofile)";

const char *default_link =
"gcc $(objects) -o $(efile)";
