@echo off

set install_location=c:\\mstools\bin
set default_objdir=..\\obj
set default_bindir=..\\bin
set default_compile=cl -c $(cfile) /Fo$(ofile)
set default_link=link -out:$(efile) $(objects)

if %1.==configure. goto do_configure
if %1.==build. goto do_configure
if %1.==install. goto do_configure
if %1.==publish. goto do_publish

echo Usage:  run [install  build  publish]
echo.
echo   run install
echo       This will do everything you need, configuring and building
echo       the clump program and publishing it in $install_location.
echo.
echo       [Note:  If you want to change where clump is installed, just
echo       change the install_location variable at the top of this \"run\"
echo       script.]
echo.
echo   run configure
echo       This configures clump based on your operating system.
echo.
echo   run build
echo       Use this if you just want to recompile clump in your ../bin
echo       directory without publishing it in $install_location.
echo       Note:  Once you've built clump this way, from then on you can
echo       use clump to build itself and you no longer need this script.
echo.
echo   run publish
echo       Publish the already built clump into $install_location.
echo.

goto end

: do_configure

echo Configuring clump

echo /* This file generated by "run configure" */ >config.h
echo #define USE_WINDOWS 1 >>config.h

echo /* This file generated by "run configure" */ >clump.h
echo. >>clump.h
echo const char *default_objdir = "%default_objdir%"; >>clump.h
echo const char *default_bindir = "%default_bindir%"; >>clump.h
echo. >>clump.h
echo const char *default_compile = >>clump.h
echo "%default_compile%"; >>clump.h
echo. >>clump.h
echo const char *default_link = >>clump.h
echo "%default_link%"; >>clump.h

if %1.==build. goto do_build
if %1.==install. goto do_build
goto end

: do_build

cl -c bufd.c /Fo..\obj\bufd.o
cl -c strq.c /Fo..\obj\strq.o
cl -c clump.c /Fo..\obj\clump.o
cl -c getopt.c /Fo..\obj\getopt.o
cl -c dir.c /Fo..\obj\dir.o
link -out:..\bin\clump.exe ..\obj\clump.o ..\obj\bufd.o ..\obj\strq.o ..\obj\getopt.o ..\obj\dir.o

if %1.==install. goto do_publish
goto end

: do_publish

echo Publish clump in %install_location%
copy ..\bin\clump.exe %install_location%

: end
